#!/usr/bin/env python3

import colors as s

print("This is the completing the square calculator.")

a = float(input("What is the 'a' value of the quadratic function? > "))
b = float(input("What is the 'b' value of the quadrtaic function? > "))
c = float(input("What is the 'c' value of the quadratic function? > "))

if a >= 2:
    print("Divide everything by "+str(a))
    new = (a/a) + (b/a)
    other_side = (c/a)

else:
    new = a + b
    other_side = c

missing_c = (b/2)**2
print(str(a),"+",str(b),"=",str(other_side))
print(str(new),"=",str(other_side))
new = a + b + missing_c
other_side = c + missing_c
print(str(a),"+",str(b),"+",str(missing_c),"=",str(other_side),"+",str(missing_c))
print(str(new),"=",str(other_side))


