#!/usr/bin/env python3

import colors as c

radicand = int(input("What is the radicand(b)? > "))
index = int(input("What is the index(n)? > "))

def nth_root(val, n):
    ret = int(val**(1./n))
    return ret + 1 if (ret + 1) ** n == val else ret

print(nth_root(radicand, index))
