#!/usr/bin/env python3

import colors as c

odd = [3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49]
even = [2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50]

simplify = input(c.yellow+"Would you like your answer to be simplified? y/n > ").lower().strip()

def nth_root(radicand, index):
    if radicand == 0:                                                                                                                               
        print("The only real nth root of 0 is 0.")                                                                                              
    if index in odd:                                                                                                                            
        if radicand > 0:                                                                                                                        
            answer = radicand ** (1./float(index))                                                                                                
        if radicand < 0:                                                                                                                            
            answer = -(-radicand) ** (1./float(index))                                                                                          
    if index in even: 
        if radicand > 0:
            answer = radicand ** (1./float(index))                                                                                            
        if radicand < 0:            
            print("There are no real roots")  
    return answer + 1 if (answer + 1) ** index == radicand else answer 

if simplify == "y":
    print("This part of the calculator is currently not functional. Try again later!")
    exit

if simplify == "n":
    b = int(input("What is the number under the radical?(b) > "))
    n = int(input("What is the degree of the root?(n) > "))
    print(nth_root(b, n))
