#!/usr/bin/env python3

import skilstak.colors as s

'''A simple quadratic calculator that uses the quadratic formula. Can give decimal answers, or answers with simplified radicals'''

print(s.green+"This is a calculator to solve a quadratic equation in standard form using the quadratic formula")
print("")

a = float(input("What is the 'a' value of the quadratic equation? > "))
b = float(input("What is the 'b' value of the quadratic equation? > "))
c = float(input("What is the 'c' value of the quadratic equation? > "))
print("")
simplify = input("Would you like to simplify your radical? y/n > ").lower()

discrim = (b**2+(-4*a*c))

persq = [4,9,16,25,36,49,64,81,100,121,144,169,196,225,256,289,324,361,400]

def simpleradi(radical):
    negative = False
    global simplified
    if radical < 0:
        radical = radical * -1
        negative = True
    for num in persq[::-1]:
        if negative == True:
            if radical in persq:
                simplified = str(radical ** (1/2))+"i"
                break
            elif radical % num <= 0:
                simplified = (str(num ** (1/2))+"i√"+str(radical/num))
                break
        else:
            if radical in persq:
                simplified = str(radical ** (1/2))
                break
            elif radical % num <= 0:
                simplified = (str(num ** (1/2))+"√"+str(radical/num))
                break
    else:
        if negative == True:
            simplified = "i√" + str(radical)
        else:
            simplified = "√" + str(radical)

if simplify == "y":
    simpleradi(discrim)

newb = -1*(b)
over2a = 2*a
sqrtdiscrim = discrim**(1/2)
solution1p1 = (newb) + (sqrtdiscrim)
solution2p1 = (newb) - (sqrtdiscrim)
solution1p2 = solution1p1/over2a
solution2p2 = solution2p1/over2a

def solve():
    if discrim == 0:
        print("One real solution = x = ", end = '')
        print(solution1p2)
    if discrim > 0:
        print("Two real solutions = x = ", end = '')
        print(solution1p2,",",solution2p2)

print("")
print("discrim = b²-4ac")
print("discrim = ("+str(b)+")²-4("+str(a)+")("+str(c)+")")
print("discrim = ", discrim)
print("")

def quadform():
    print("x = -b ±√b²-4ac")
    print("    --------------")
    print("          2a      ")
    print("")
    print("x =", str(newb)+" ±√("+str(b)+")²-4("+str(a)+")("+str(c)+")")
    print("    ----------------------------")
    print("              2("+str(a)+")")
    print("")
    print("x =",str(newb)+" ±√"+str(discrim))
    print("    -------------")
    print("        ",over2a)
    
    
def simplified_answer():
    print(str(newb)+" ±"+simplified)
    print("    -------------")
    print("      ",over2a)

if simplify == "y":
    if discrim in persq:
        quadform()
        print("")
        print("x = ", end='')
        simplified_answer()
        solve()
    else:
        if discrim < 0:
            quadform()
            print("")
            print("No real solutions!")
            print("The 2 non real solutions are =")
            print("x = ", end='')
            simplified_answer()
        if discrim == 0:
            quadform()
            print("")
            print("One real solution = ")
            print("x = ", end='')
            simplified_answer()
        if discrim > 0:
            quadform()
            print("")
            print("Two real solutions = ")
            print("x = ", end='')
            simplified_answer()

else:
    if discrim < 0:
        print("No real solutions!")
    if discrim == 0:
        quadform()
        print("")
        solve()
    if discrim > 0:
        quadform()
        print("")
        solve()
