#!/usr/bin/env python3

import skilstak.colors as s
from mathy import simpleradi

print(s.green+"This is a calculator to solve a quadratic equation in standard form using the quadratic formula")
print("")

a = float(input("What is the 'a' value of the quadratic equation? > "))
b = float(input("What is the 'b' value of the quadratic equation? > "))
c = float(input("What is the 'c' value of the quadratic equation? > "))

simplify = input("Would you like to simplify your radical? y/n ").lower()

discrim = (b**2+(-4*a*c))

if simplify == "y":
    simpleradi()

newb = -1*(b)
over2a = 2*a
sqrtdiscrim = discrim**(1/2)
solution1p1 = (newb) + (sqrtdiscrim)
solution2p1 = (newb) - (sqrtdiscrim)
solution1p2 = solution1p1/over2a
solution2p2 = solution2p1/over2a

def solve():
    if discrim == 0:
        print("One real solution = x = ", end = '')
        print(solution1p2)
    if discrim > 0:
        print("Two real solutions = x = ", end = '')
        print(solution1p2,",",solution2p2)

print("")
print("discrim = b²-4ac")
print("discrim = ("+str(b)+")²-4("+str(a)+")("+str(c)+")")
print("discrim = ", discrim)
print("")

def quadform():
    print("x = -b ±√b²-4ac")
    print("    --------------")
    print("          2a      ")
    print("")
    print("x =", str(newb)+" ±√("+str(b)+")²-4("+str(a)+")("+str(c)+")")
    print("    ----------------------------")
    print("              2("+str(a)+")")
    print("")
    print("x =",str(newb)+" ±√"+str(discrim))
    print("    -------------")
    print("        ",over2a)
    
    
def simplified_answer():
        print("Two real solutions = x = ", end = '')
        print("x =",str(newb)+" ±"+simplified)
        print("    -------------")
        print("        ",over2a)

if simplify == "y":
    if discrim < 0:
        quadform()
        print("No real solutions!")
        print("The 2 non real solutions are = ")
        simplified_answer()
    if discrim == 0:
        quadform()
        print("One real solution = x = ")
        simplified_answer()
    if discrim > 0:
        quadform()
        print("Two real solutions = x = ")
        simplified_answer()
        
elif simplify == "n":
    if discrim < 0:
        print("No real solutions!")
        print("The non real solutions are = ", end = '')
    if discrim == 0:
        quadform()
        print("")
        solve()
    if discrim > 0:
        quadform()
        print("")
        solve()
