#!/usr/bin/env python3

import sys

radical = int(sys.argv[1])
print("radical=",radical)
persq = [4,9,16,25,36,49,64,81,100,121,144,169,196,225,256,289,324,361,400]
for num in persq[::-1]:
    print("num=",num)
    if radical < 0:
        radical = radical * -1
        if radical in persq:
            print(str(radical ** (1/2))+"i")
            break
        if radical % num <= 0:
            print("Made it")
            print(str(num ** (1/2))+"i√"+str(radical/num))
            break
    elif radical > 0:
        if radical in persq:
            print(radical ** (1/2))
            break
        if radical % num <= 0:
            print(str(num ** (1/2))+"√"+str(radical/num))
            break
