#!/usr/bin/env python3

a = float(input("Please insert your 'a' value of the first system > "))
b = float(input("Please insert your 'b' value of the first system > "))
c = float(input("Please insert your 'c' value of the first system > "))
a1 = float(input("Please insert your 'a' value of the second system > "))
b1 = float(input("Please insert your 'b' value of the second system > "))
c1 = float(input("Please insert your 'c' value of the second system > "))
