#!/usr/bin/env python3

import colors as c

equation = "a * (f(x) + b) + c"

def ask_function():
    global equation
    print("Which kind of function is the equation?")
    while True:
        selection = {"A":"x","B":"(x² + b)","C":"(x³ + b)","D":"√(x + b)","E":"|x + b|"}
        print("A: Linear\nB: Quadratic\nC: Cubic\nD: Square Root\nE: Absolute Value")
        function_selection = input("> ").upper().strip()
        if function_selection not in selection:
            print(c.clear + "Please choose a valid function.")
            continue
        else:
            equation = equation.replace("(f(x) + b)",selection[function_selection])
            print(equation)
            break

def get_var():
    global a,b,c,equation
    a = float(input("What is the 'a' value of the function? Please use decimals instead of fractions. > "))
    equation = equation.replace("a",str(a))
    b = float(input("What is the 'b' value of the function? Please use decimals instead of fractions. > "))
    equation = equation.replace("b",str(b))
    c = float(input("What is the 'c' value of the function? Please use decimals instead of fractions. > "))
    equation = equation.replace("c",str(c))
    print(equation)

def find_values(equation):
    xdomain = 
    yrange = 
    ioi = 
    iod = 
    extrema = 
    end_behavior = 

try:
    ask_function()
    get_var()
except KeyboardInterrupt:
    print("Thank you for using the program!")
    exit()
