#!/usr/bin/env python3

import colors as c
import math

def trig_ex():
    print("""
                SohCahToa
                ---------
    |\\         sin = opposite/hypotenuse | sin1 = s1/s3 | sin2 = s2/s3
    |1\\        cos = adjacent/hypotenus  | cos1 = s2/s3 | cos2 = s1/s3
 s2 |  \\ s3    tan = opposite/adjacent   | tan1 = s1/s2 | tan2 = s2/s1
    |   \\
    |   2\\
    -------
      s1
    """)

def inputting_values():
    angle, mangle = input("What is the angle, and what is it's measure? Ex.1, 70. If it is unknown, type 1, N/A. > ").split(', ')
    function = input("What is the kind of function you would like to use to find the angle/side? (sin, cos, tan) > ")
    if mangle == "N/A":
        s1, s2 = float(input("What are the two sides, according to " + function + "? Ex.12, 14 results in 12/14 > "). split(', '))
        inverse = True
    else:
        s1 = float(input("What is the known side? > "))
        inverse = False
        s2 = "N/A"
    return function, s1, s2, inverse, float(mangle)

def solve(function, side1, side2, inverse, mangle):
    #if inverse == True:
    #    if function
    if inverse == False:
        sins1 = math.sin(math.radians(mangle))
        if function == "sin":
            side_type = input("Is " + side1 + "the opposite side of the angle or the hypostenuse of the triange? opp/hyp > ")
            if side_type == "opp":
                side = math.degrees(side1/sins1)
            elif side_type == "hyp":
                side = math.degrees(side1*sins1)
        elif function == "cos":
            side_type = input("Is " + side1 + "the adjacent side of the angle or the hypostenuse of the triange? adj/hyp > ")
            if side_type == "adj":
                side = math.degrees(side1/sins1)
            elif side_type == "hyp":
                side = math.degrees(side1*sins1)
        elif function == "tan":
            side_type = input("Is " + side1 + "the opposite side of the angle or the adjacent side? opp/adj > ")
            if side_type == "opp":
                side = math.degrees(side1/sins1)
            elif side_type == "adj":
                side = math.degrees(side1/sins1)
        answer = side
    return answer
            
print("This is a trigonometry calculator.")
trig_ex()
function, side1, side2, inverse, mangle = inputting_values()
answer = solve(function, side1, side2, inverse, mangle)
print(answer)
