#!/usr/bin/env python3

import colors as c
import requests

def get_currency_exchange_rate(base,target):
    if base == target:
        return 1
    api_uri = "https://api.fixer.io/latest?base={}&symbols={}".format(base, target)
    api_response = requests.get(api_uri)
    if api_response.status_code == 200:
        return api_response.json()["rates"][target]

if __name__ == '__main__':
    print(c.clear+c.orange+"Welcome to a currency converter!")
    print("Please select the options:")
    print("A: USD to RUB")
    print("B: RUB to USD")
    choice = input("Please select the method of conversion > ").upper().strip()
    if choice == "A":
        amt = float(input("Please insert the amount of dollars you would like to convert into rubels > "))
        exchange_rate = get_currency_exchange_rate("USD", "RUB")
        print("{} {} is {} {}".format(amt, "USD", amt * exchange_rate, "RUB"))
    if choice == "B":
        amt = float(input("Please insert the amount of rubels you would like to convert into dollars > "))
        exchange_rate = get_currency_exchange_rate("RUB", "USD") 
        print("{} {} is {} {}".format(amt, "RUB", amt * exchange_rate, "USD"))

