#!/usr/bin/env python3

print("Welcome to 2 player hangman!")
the_word = input("Please write the word that you want the guesser to guess. > ").lower()
progress = list(word)
tries = 6
letters_used = ""
def progress_updater(self, guess, word, progress):
    i = 0
    while i < len(the_word):
        if guess == the_word[i]
            progress[i] = guess
            i += 1
        else:
            i += 1
    return "".join(progress)

while tries > 0:
    guess = input("Guess a letter > ")
    if guess in the_word and not in letters_used:
        letters_used += ","
        print("Progress: " + progress_updater)
        print("Letters used: " + letters_used)
    elif guess not in the_word and not in letters_used:
        tries -=1
        letters_used += ","
        print("Progress: " + progress_updater)
        print("Letters used: " letters_used)
    else:
        continue
                  
    

