#!/usr/bin/env python3

import colors as c
import random
import time

print("Hello and welcome to the casino where we play blackjack!")
rules = input("Would you like to read the rules? y/n > ").lower()
score = 0

def print_rules():
    print("\nThe goal of blackjack is to score 21 by adding up all of your cards.")
    print("You can draw for more points.")
    print("All face cards are worth 10 points. Aces are ONLY 1 point.\n")
    time.sleep(1)

def get_card_value(card):
    if card == 'Ace':
        return 1
    elif card.isdigit() and (1 < int(card) < 10):
        return int(card)
    elif card == 'Jack' or 'Queen' or 'King':
        return 10

def play():
    hand = []
    cards = ['Ace', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'Jack', 'Queen', 'King']
    card1 = random.choice(cards)
    card2 = random.choice(cards)
    hand.append(get_card_value(card1))
    hand.append(get_card_value(card2))
    print('Your hand is {} for a value of '.format(str(card) for card in hand) + sum(hand))
    while score <= 21:
        score = sum(hand)
        draw = input('Would you like another card? y/n > ').lower()
        if draw == 'y':
            new_card = random.choice(card)
            hand.append(get_card_value(new_card))

if rules == "y":
    print_rules()
play()
