#!/usr/bin/env python3

import colors as c

def draw_board(board):
    print('1|2|3|4')
    print('-------')
    print(board[0] + '|' + board[1] + '|' + board[2] + '|' + board[3])
    print(board[4] + '|' + board[5] + '|' + board[6] + '|' + board[7])
    print(board[8] + '|' + board[9] + '|' + board[10] + '|' + board[11])
    print(board[12] + '|' + board[13] + '|' + board[14] + '|' + board[15])

def drop(col,p):
    for n,i in reversed(list(enumerate(col))):
        if i == ' ':
            col[n] = p
            break
        if ' ' not in col:
            print('Invalid Move!')
            break
        print(col)

def turn(board,choice):
    if player == 1:
        piece = 'X'
    if player == 2:
        piece = 'O'

    if choice == 1:
        col1 = []
        col1.extend((board[0],board[4],board[8],board[12]))
        drop(col1,piece)
        board[12] = col1[3]
        board[8] = col1[2]
        board[4] = col1[1]
        board[0] = col1[0]
    
    if choice == 2:
        col2 = []
        col2.extend([board[1],board[5],board[9],board[13]])
        drop(col2,piece)
        board[13] = col2[3]
        board[9] = col2[2]
        board[5] = col2[1]
        board[1] = col2[0]

    if choice == 3:
        col3 = []
        col3.extend([board[2],board[6],board[10],board[14]])
        drop(col3,piece)
        board[14] = col3[3]
        board[10] = col3[2]
        board[6] = col3[1]
        board[2] = col3[0]
    
    if choice == 4:
        col4 = []
        col4.extend([board[3],board[7],board[11],board[15]])
        drop(col4,piece)
        board[15] = col4[3]
        board[11] = col4[2]
        board[7] = col4[1]
        board[3] = col4[0]
        

def check_win(board):
    row1 = board[12] == board[13] == board[14] == board[15]
    row2 = board[8] == board[9] == board[10] == board[11]
    row3 = board[4] == board[5] == board[6] == board[7]
    row4 = board[0] == board[1] == board[2] == board[3]
    col1 = board[12] == board[8] == board[4] == board[0]
    col2 = board[13] == board[9] == board[5] == board[1]
    col3 = board[14] == board[10] == board[6] == board[2]
    col4 = board[15] == board[11] == board[7] == board[3]
    diag1 = board[12] == board[9] == board[6] == board[3]
    diag2 = board[15] == board[10] == board[5] == board[0]
    if row1 or row2 or row3 or row4 or col1 or col2 or col3 or col4 or diag1 or diag2:
       return True
    else:
        return False

try:
    player = 1
    board = [' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']
    while True:
        draw_board(board)
        choice = int(input('Which column? > '))
        turn(board,choice)
        if check_win(board) == True:
           print('Player ' + str(player) + ' wins!')
        if player == 1:
            player = 2
            continue
        if player == 2:
            player = 1
            continue
except KeyboardInterrupt:
    print('\nThanks for playing!')
