#!/usr/bin/env python3

import random

def draw_ball():
    print('''          _.-----._
       .-'         `-.
     .'     _..._     `.
    :     .' .-. `.     :
   :     :  :   :  :     :
  :      :  :   :  :      :
  :       `._`-'_.'       :
  :       .' .-. `.       :
  :      :  :   :  :      :
   :     :  :   :  :     :
    :     `._`-'_.'     :
     `.      \'\''      .'
       `-._       _.-'
           `-----''')

def select_fortune():
    fortunes = ['affirmative','non_commital','negative']
    affirmative = ['It is certain','It is decidedly so','Without a doubt','Yes, definitely','You may rely on it','As I see it, yes','Most likely','Outlook good','Yes','Signs point to yes','Ch\'yas']
    non_commital = ['Reply hazy, try again later','Ask again later','Better not tell you now','Cannot predict now','Concentrate harder on your question, and ask agian later']
    negative = ['Don\'t count on it','My reply says no','My sources say no','Outlook no so good','Very doubtful']
    selected_type = random.randint(0,2)
    fortune_type = fortunes[selected_type]
    fortune = random.choice(fortune_type)

while True:
    try:
        while True:
            draw_ball()
            choice = input('Would you like your fortune? y/n > ').lower()
            if choice == 'n':
                print('Suit yourself, no refunds!')
                exit()
            else:
                ask = input('What is your question? > ')
                select_fortune()
                print(fortune)
                continue
    except KeyboardInterrupt:
        print('\n')
        print('Suit yourself, no refunds!')
        exit()


