#!/usr/bin/env python3

import colors as c
import random
import time

def draw_ball():
    print('''          _.-----._
       .-'         `-.
     .'     _..._     `.
    :     .' .-. `.     :
   :     :  :   :  :     :
  :      :  :   :  :      :
  :       `._`-'_.'       :
  :       .' .-. `.       :
  :      :  :   :  :      :
   :     :  :   :  :     :
    :     `._`-'_.'     :
     `.      \'\''      .'
       `-._       _.-'
           `-----''')

def select_fortune():
    fortunes = ('It is certain','It is decidedly so','Without a doubt','Yes, definitely','You may rely on it','As I see it, yes','Most likely','Outlook good','Yes','Signs point to yes','Ch\'yas','Reply hazy, try again later','Ask again later','Better not tell you now','Cannot predict now','Concentrate harder on your question, and ask agian later','Don\'t count on it','My reply says no','My sources say no','Outlook no so good','Very doubtful')
    fortune_no = random.randint(0,20)
    fortune = fortunes[fortune_no]
    print(fortune)

while True:
    try:
        while True:
            print(c.clear + 'Welcome to the all mighty and omniscient "Magic 8 Ball!"')
            draw_ball()
            choice = input('Would you like your fortune? y/n > ').lower()
            if choice == 'n':
                print('Suit yourself, no refunds!')
                exit()
            else:
                ask = input('What is your question? > ').lower()
                select_fortune()
                print('Resetting...')
                time.sleep(3)
                continue
    except KeyboardInterrupt:
        print('')
        print('Suit yourself, no refunds!')
        exit()


