#!/usr/bin/env python3

import skilstak.colors as c
import random

print("It's time to play hangman!")
bank = ['hangman', 'bodywash', 'fairy', 'wizard', 'python', 'coding']
word = random.choice(bank)
guesses = 0

while guesses < 6:
    guess = input("Which letter will you guess? > ")
    if guess in word:
        print("This letter is in the word!")
    else:
        guess += 1
    if guesses == 5:
        print("You lose!")
