#!/usr/bin/env python3

import colors as c
import random
import sys

print("It's time to play hangman!")
word = input("Player 1, please insert the word for Player 2 to guess > ").lower()
guesses = 6
x = 0
hidden_word = [' _ ']* len(word)
guessed = []
ascii = [''' |-----|
       |
       |
      ---''',
         ''' |-----|
 0     |
       |
      ---''',
         ''' |-----|
 0     |
 |     |
      ---''',
         ''' |-----|
 0     |
/|     |
      ---''',
         ''' |-----|
 0     |
/|\    |
      ---''',
         ''' |-----|
 0     |
/|\    |
/     ---''',         
          ''' |-----|
 0     |
/|\    |
/ \   ---''']
while guesses <= 6:
    print(ascii[x])
    print("Guesses left = "+str(guesses))
    print("Letters used =",str(guessed))
    print(hidden_word)
    guess = input("Which letter will you guess? > ").lower().strip()
    while guess in guessed:
        print("You've already guessed this letter!")
        guess = input("Which letter will you guess? > ").lower()
    guessed.append(guess)
    if guess in word:
        print("This letter is in the word!")
        if len(guess) > 1:
        	guesses -= 1
        	x += 1
        for letter in range(len(word)):
            if guess == word[letter]:
                hidden_word[letter] = guess
                if ' _ ' not in hidden_word:
                    print(hidden_word)
                    print("You win!")
                    print("The word was",word+"!")
                    sys.exit()
    if guesses == 1:
        x += 1
        print(ascii[x])
        print("You lose!")
        sys.exit()
    elif guess not in word:
        guesses -= 1
        x += 1
        continue