#!/usr/bin/env python3

import random

weapon_bank = ["rock","paper","scissors"]
win_talley = 0

def rockpaperscissors():
    while True:
        usr_input("Would you like to play rock paper scissors? y/n > " ).lower().strip()
        if usr_input() == "y":
            selection = input("Rock, paper, or scissors? > ")
            computer_select = random.choice(weapon_bank)
            if selection == "rock":
                if computer_select == "scissors":
                    print("You win!")
                    win_talley += 1
                    print("Wins = ",win_talley)
                    continue
                elif computer_select == "rock":
                    print("Tie!")
                    print("Wins = ",win_talley)
                    continue
                elif computer_select == "paper":
                    print("You lost!")
                    print("Wins = ",win_talley)
                    continue
            if selection == "paper":
                if computer_select == "scissors":
                    print("You lost!")
                    print("Wins = ",win_talley)
                if computer_select == "rock":
                    print("You win!")
                    win_talley += 1
                    print("Wins = ",win_talley)
                if computer_select == "paper":

