#!/usr/bin/env python3

import random

def rockpaperscissors():
    win_talley = 0
    while True:
        weapon_bank = ['rock','paper','scissors']
        usr_input = input("Would you like to play rock paper scissors? y/n > " ).lower().strip()
        if usr_input == "y":
            selection = input("Rock, paper, or scissors? > ").lower().strip()
            computer_select = random.choice(weapon_bank)
            if selection == "rock" or "r":
                if computer_select == "scissors":
                    print("You win!")
                    win_talley += 1
                    print("Wins = ",win_talley)
                    continue
                elif computer_select == "rock":
                    print("Tie!")
                    print("Wins = ",win_talley)
                    continue
                elif computer_select == "paper":
                    print("You lost!")
                    print("Wins = ",win_talley)
                    continue
            if selection == "paper" or "p":
                if computer_select == "scissors":
                    print("You lost!")
                    print("Wins = ",win_talley)
                    continue
                if computer_select == "rock":
                    print("You win!")
                    win_talley += 1
                    print("Wins = ",win_talley)
                    continue
                if computer_select == "paper":
                    print("Tie!")
                    print("Wins = ",win_talley)
                    continue
            if selection == "scissors" or "s":
                if computer_select == "scissors":
                    print("Tie!")
                    print("Wins = ",win_talley)
                    continue
                if computer_select == "rock":
                    print("You lost!")
                    print("Wins = ",win_talley)
                    continue
                if computer_select == "paper":
                    print("You win!")
                    win_talley += 1
                    print("Wins = ",win_talley)
                    continue
            else:
                break
        else:
            break

rockpaperscissors()
