#!/usr/bin/env python3

import skilstak.colors as c
import random

print("This is a word scramble game.")
x = input("Would you like easy or hard mode? > ").lower()

if x == "easy":
    words = ("school, coding, lamp, joker, queen, basket, table, vase, gossip, couch")
    word = random.choice(words)
    correct = word
    tries = 3
    while word and tries > 0:
        print(random.shuffle(correct))
        guess = input("What is your guess? > ")
        if guess == correct:
            print("You guessed correctly!")
        else:
            tries -= 1

if x == "hard":
    words = ("automobile, television, refridgerator, countertop, granite, soundbar, magazine, shopping, remote, coaster")
    word = random.choice(words)
    correct = word
