#!/usr/bin/env python3

player1 = 'X'
player2 = 'O'
boardno = ['1','2','3','4','5','6','7','8','9']
player = 1

def drawboard(board):
    print('    |   |   ')
    print(' ' +board[6]+ '  | ' +board[7]+ ' | ' +board[8] )
    print('    |   |   ')
    print('-------------')
    print('    |   |   ')
    print(' ' +board[3]+ '  | ' +board[4]+ ' | ' +board[5] )
    print('    |   |   ')
    print('--------------')
    print('    |   |   ')
    print(' ' +board[0]+ '  | ' +board[1]+ ' | ' +board[2] )
    print('    |   |   ')

def check_win(board):
    if board[0] == board[1] == board[2]:
        return True
    if board[3] == board[4] == board[5]:
        return True
    if board[6] == board[7] == board[8]:
        return True
    if board[0] == board[3] == board[6]:
        return True
    if board[1] == board[4] == board[7]:
        return True
    if board[2] == board[5] == board[8]:
        return True
    if board[2] == board[4] == board[6]:
        return True
    if board[0] == board[4] == board[8]:
        return True
    else:
        return False

while True:
    drawboard(boardno)
    choice = str(input("Player " + str(player) + ", please select the cell of choice > "))
    if player == 1:
        for n,i in enumerate(boardno):
            if i == choice:
                boardno[n] = player1
                if check_win(boardno) == True:
                    print("Player 1 wins!")
                player = 2
    if player == 2:
        for n,i in enumerate(boardno):
            if i == choice:
                boardno[n] = player2
                if check_win(boardno) == True:
                    print("Player 2 wins!")
                player = 1
