#!/usr/bin/env python3

def draw_board(width,height):
    print('__'.join([' '] * (width + 1)))
    for i in range(height):
        print('__'.join(['|'] * (width + 1)))
    print('\n')

def winner(player):
    if player == 0:
        print("Tie!")
    else:
        print("Player " + str(player) + " wins!")

def check_row_win(row):
    if row[0] == row[1] and row[1] == row[2]:
        return row[0]
    else:
        return 0

def get_col(game,colno):
    return [game[x][colno] for x in range(3)]

def get_row(game,rowno):
    return [game[rowno]]

def check_win(game):
    slices = []
    for i in range(3):
        slices.append(get_row(game,i))
        slices.append(get_col(game,i))

    down_diagnol = [game[x][x] for x in range(3)]
    up_diagnol = [game[0][2],game[1][1],game[2][0]]
    slices.append(down_diagnol)
    slices.append(up_diagnol)

    for one_slice in slices:
        winner = check_row_win(one_slice)
        if winner != 0:
            winner = winner(winner)
            return winner

def display(game):
    d = {2: "O", 1: "X", 0: " "}
    game_string = []
    for rowno in range(3):
        new_row = []
        for colno in range(3):
            new_row.append(d[game[rowno][colno]])
        game_string.append(new_row)
    for game_string in game_string:
      print(game_string)
    
def add_piece(game,player,row,col):
    game[row][col] = player
    return game

def coordinate(usr_input):
    return usr_input - 1

def player_switch(player):
    if player == 1:
        return 2
    if player == 2:
        return 1

if __name__ == '__main__':
    game = [[0,0,0] for x in range(3)]
    display(game)
    player = 1
    winner = 0

    while True:
        print("Current player is: " + str(player))
        row = coordinate(int(input("Which row?(1,2,3) > ")))
        col = coordinate(int(input("Which column?(1,2,3) > ")))
        game = add_piece(game,player,row,col)
        display(game)
        check_win(game)
        player = player_switch(player)
 
