#!/usr/bin/env python3

import colors as c
import random

class Card:
    def __init__(self, value, suit):
        self.value = value
        self.suit = suit

def init_game():
    print("This is a program that runs the card game 'War.'")
    prompt = input("If you would like to read the rules, type `read`, otherwise, press enter. > ").lower().strip()
    if prompt == "read":
        print("""\nEach player turns up a card at the same time and the player with the higher card takes both cards and puts them, face down, on the bottom of his stack.
If the cards are the same rank, it is War. Each player turns up three cards face down and one card face up.
The player with the higher card at the end takes both piles.\n""")
    else:
        pass

def get_cards(deald):
    random.shuffle(deald)
    playerd = [card for card in deald[:26]]
    compd = [card for card in deald[26:]]
    return playerd, compd

def shuffle(playerd, compd):
    random.shuffle(playerd)
    random.shuffle(compd)

def war_turn(playerd, compd):
    while True:
        bet_player_cards = []
        for x in range(4):
            bet_card = random.choice(playerd)
            bet_player_cards.append(bet_card)
        bet_comp_cards = []
        for x in range(4):
            bet_card = random.choice(comp_card)
            bet_comp_cards.append(bet_card)
        if bet_player_cards[-1][0] > bet_comp_cards[-1][0]:
            for card in bet_comp_cards:
                playerd.append(card)
                compd.remove(card)
            break
        elif bet_comp_cards[-1][0] > bet_player_cards[-1][0]:
            for card in bet_player_cards:
                compd.append(card)
                playerd.remove(card)
            break
        elif bet_player_cards[-1][0] == bet_comp_card[-1][0]:
            continue


def turn(playerd, compd):
        shuffle(playerd, compd)
        player_card = random.choice(playerd)
        comp_card = random.choice(compd)
        print("Your card is a {}, while your opponents is a {}.".format(player_card, comp_card).replace("(","").replace("'","").replace(")",""))
        if player_card > comp_card:
            print("You gained your opponents card!")
            playerd.append(comp_card)
            compd.remove(comp_card)
        elif comp_card > player_card:
            print("You lost a card to your opponent!")
            compd.append(player_card)
            playerd.remove(player_card)
        elif player_card[0] == comp_card[0]:
            print("It's a war!")
            war_turn(playerd, compd)
            
def check_win(playerd, compd):
    if len(playerd) or len(compd) == 0:
        return True
    else:
        return False

if __name__ == "__main__":
    suits = ["diamond","heart","club","spade"]
    class_deck = [Card(value, suit) for value in range(2,15) for suit in suits]
    dealing_deck = []
    cards = {2:"2", 3:"3", 4:"4", 5:"5", 6:"6", 7:"7", 8:"8", 9:"9", 10:"10", 11:"Jack", 12:"Queen", 13:"King", 14:"Ace"}
    for card in class_deck:
        dealing_deck.append((cards[card.value], card.suit))
    try:
        init_game()
        player_deck, comp_deck = get_cards(dealing_deck)
        win = check_win(player_deck, comp_deck)
        while win == False:
            turn(player_deck, comp_deck)
            win = check_win(player_deck, comp_deck)
            input("Press enter to continue > ")
        if win == True:
            if len(comp_deck) == 0:
                print("You Win!")
                exit()
            if len(player_deck) == 0:
                print("You Lost!")
                exit()
    except KeyboardInterrupt:
        exit()
