#!/usr/bin/env python3

import random

def randomupper(char):
    if random.random() > 0.5:
        return char.upper()
    return char.lower()

print("How long would you like your password?")
amt = int(input("> "))
passwd = ''

characters = ['q',
'w',
'e',
'r',
't',
'y',
'u',
'i',
'o',
'p',
'a',
's',
'd',
'f',
'g',
'h',
'j',
'k',
'l',
'z',
'x',
'c',
'v',
'b',
'n',
'm',
'1',
'2',
'3',
'4',
'5',
'6',
'7',
'8',
'9',
'0',
'!',
'@',
'#',
'$',
'%',
'&',
'*',
'?',
'~']

for num in range(amt):
    char = random.choice(characters)
    passwd = passwd + char

print("Your password is: " + ''.join(map(randomupper, passwd)))
