#!/usr/bin/env python3

from urllib.request import urlopen
from urllib.parse import quote
import json

text = input("Please insert the text you would like to translate? > ")
key = 'trnsl.1.1.20161115T000957Z.bfd226ab9528dc17.1187644df314fbac431ed567b4b6704da11c5e5f'
lang = 'en-ru'
url = "https://translate.yandex.net/api/v1.5/tr.json/translate?key=" + key + "&text=" + text + "&lang=" + lang
with urlopen(url) as response:
    raw = response.read().decode('utf-8')
    data = json.loads(raw)
    print(text + " = " + data['text'][0])
