#!/usr/bin/env python3

import colors as c
import random

def roll_dice(nums):
    num = random.randint(0,5)
    print('-----------')
    print('|         |')
    print('|    ' + nums[num] + '    |')
    print('|         |')
    print('-----------')

nums = ['1','2','3','4','5','6']
while True:
    roll_dice(nums)
    again = input('Would you like to roll the dice again? y/n > ').lower()
    if again == 'n':
        break
