#!/usr/bin/env python3

import curses
import time

stdscr = curses.initscr()
stdscr.keypad(True)
stdscr.clear()
begin_x = 20; begin_y = 7
height = 5; width = 40
win = curses.newwin(height, width, begin_y, begin_x)
time.sleep(5)
stdscr.keypad(False)
curses.echo()
curses.endwin()
