#!/usr/bin/env python3

import time

timeset = input("How long would you like to set the timer for? > ")

def current_time():
    seconds = 0
    minutes = 0
    while True:
        time.sleep(1)
        if seconds == 59:
            seconds = 0
            minutes += 1
        else:
            seconds += 1

while timeset > current_time():
    current_time()

if timeset == current_time():
    print("Times up bubba!")

