#!/usr/bin/env python3

import skilstak.colors as c
import time

seconds = 0
minutes = 0
continued = 0
print(" This is a stopwatch. Press Ctrl+C to stop the timer.")
try:
    while continued != 1:
        print("",minutes, ':', seconds)
        time.sleep(1)
        if seconds == 59:
            seconds = 0
            minutes += 1
        else:
            seconds += 1
except KeyboardInterrupt:
    print(c.clear,minutes, ':', seconds)
