#!/usr/bin/env python3

import time
import skilstak.colors as c

time_input = int(input("Please input the amount of time you would like to set on the timer in seconds > "))
current = 0

while current <= time_input:
    print(current)
    time.sleep(1)
    current += 1

print(c.multi("DING DING DING"))

