#!/usr/bin/env python3

import time
import skilstak.colors as c

def tpass():
    minutes = 0
    seconds = 0
    continued = 0
    while continued != 1:
        time.sleep(60)
        if seconds == 59:
            seconds = 0
            minutes += 1
        else:
            seconds += 1

timer = input("How long would you like to set the timer for? > ")

while tpass() < timer:
    tpass()
    timer -= 60

if tpass() == timer:
    print("Times Up! BING BING BING BING")

