#!/usr/bin/env python3

col = ['','','','']


while True:
    choice = int(input('Which column will you choose? > '))

    if choice == 1:
        for n,i in reversed(list(enumerate(col))):
            if i == '':
                col[n] = 'X'
                break
            if '' not in col:
                print('Invalid Move!')
                break
        print(col)
