#!/usr/bin/env python3

col = ['','','','']

def drop(p,col):
    n = 0
    bottom = len(col) - 1
    while n <= len(col):
        if n == bottom:
            col[n] = p
        if n == '':
            n += 1
            continue
        else:
            if n > 0:
                col[n-1] = p
        n += 1
       
def view(col):
    for n in col:
        print(n)

drop('x',col)
view(col)
